import { ASSETS } from "@/lib/assets";

const ICON_BASE_URL = ASSETS.ICONS.BASE_URL;

export const initialCategories = [
  {
    id: 1,
    title: 'Speaking',
    description: 'Speak Better',
    icon: `${ICON_BASE_URL}/ic-speaking.png`,
    code: 'speaking',
    scoring_type: 'auto',
    short_name: '',
    first_question_id: null,
    color: '',
    parent: null,
    practice_count: 0,
    question_count: 0,
    video_link: '',
  },
  {
    id: 2,
    title: 'Read Aloud',
    description:
      'Please examine the text provided below. You are required to read it out loud as naturally as you can. Remember, you only have 40 seconds to complete this task.',
    icon: `${ICON_BASE_URL}/s_read_aloud_production.png`,
    code: 's_read_aloud',
    scoring_type: 'ai',
    short_name: 'RA',
    first_question_id: 618,
    color: '#ED5D5C',
    parent: 1,
    practice_count: 0,
    question_count: 392,
    video_link: 'https://youtu.be/1N2KOt4mHwE',
  },
  {
    id: 3,
    title: 'Repeat Sentence',
    description:
      "You're about to hear a sentence. Please repeat it exactly as you hear it. Keep in mind, you will only hear the sentence one time.",
    icon: `${ICON_BASE_URL}/s_repeat_sentence_production.png`,
    code: 's_repeat_sentence',
    scoring_type: 'ai',
    short_name: 'RS',
    first_question_id: 2853,
    color: '#FF6668',
    parent: 1,
    practice_count: 0,
    question_count: 405,
    video_link: 'https://youtu.be/tL0sRPdpNN4',
  },
  {
    id: 4,
    title: 'Describe Image',
    description:
      "Please examine the image provided below. You have 25 seconds to prepare, then speak into the microphone and describe in detail what you see in the image. Remember, you'll have 40 seconds to give your complete response.",
    icon: `${ICON_BASE_URL}/s_describe_image_production.png`,
    code: 's_describe_image',
    scoring_type: 'ai',
    short_name: 'DI',
    first_question_id: 3744,
    color: '#FF7747',
    parent: 1,
    practice_count: 0,
    question_count: 205,
    video_link: 'https://youtu.be/_jNUTdyemgs',
  },
  {
    id: 5,
    title: 'Retell Lecture',
    description:
      "You're going to hear a lecture. After listening to it, you'll have 10 seconds to prepare. Then, please speak into the microphone and summarise what you've just heard from the lecture in your own words. Remember, you'll have 40 seconds to provide your response.",
    icon: `${ICON_BASE_URL}/s_retell_lecture_production.png`,
    code: 's_retell_lecture',
    scoring_type: 'ai',
    short_name: 'RL',
    first_question_id: 4386,
    color: '#FEAB33',
    parent: 1,
    practice_count: 0,
    question_count: 204,
    video_link: 'https://youtu.be/6jTPfOtfXNA',
  },
  {
    id: 6,
    title: 'Answer Short Question',
    description:
      "You're about to hear a question. Please provide a concise and simple answer. In many cases, just one or a few words will suffice.",
    icon: `${ICON_BASE_URL}/s_short_question_production.png`,
    code: 's_short_question',
    scoring_type: 'ai',
    short_name: 'ASQ',
    first_question_id: 5827,
    color: '#FCCC3A',
    parent: 1,
    practice_count: 0,
    question_count: 305,
    video_link: 'https://youtu.be/6jTPfOtfXNA',
  },
  {
    id: 7,
    title: 'Writing',
    description: 'Write Smarter',
    icon: `${ICON_BASE_URL}/ic-writing.png`,
    code: 'writing',
    scoring_type: 'auto',
    short_name: '',
    first_question_id: null,
    color: '',
    parent: null,
    practice_count: 0,
    question_count: 0,
    video_link: '',
  },
  {
    id: 8,
    title: 'Summarize Written Text',
    description:
      'Please read the passage below and summarize it using only one sentence. Type your response in a box at the bottom of the screen. Remember, you have 10 minutes to complete this task. Your response will be evaluated based on the quality of your writing and how effectively you have captured the key points from the passage.',
    icon: `${ICON_BASE_URL}/w_summarize_text_production.png`,
    code: 'w_summarize_text',
    scoring_type: 'ai',
    short_name: 'SWT',
    first_question_id: 6412,
    color: '#70C077',
    parent: 7,
    practice_count: 0,
    question_count: 154,
    video_link: 'https://youtu.be/C4aY4_dpNjs',
  },
  {
    id: 9,
    title: 'Essay',
    description:
      'For the following topic you are expected to compose a comprehensive and well-structured essay. Your essay should demonstrate your understanding of the topic, provide arguments or viewpoints, and conclude in a meaningful way. The quality of your writing, coherence of ideas, and validity of your arguments will contribute to your final score.',
    icon: `${ICON_BASE_URL}/w_essay_production.png`,
    code: 'w_essay',
    scoring_type: 'ai',
    short_name: 'WE',
    first_question_id: 6673,
    color: '#ACD47E',
    parent: 7,
    practice_count: 0,
    question_count: 150,
    video_link: 'https://youtu.be/ppivyQmoMkI',
  },
  {
    id: 10,
    title: 'Reading',
    description: 'Quick Feedback',
    icon: `${ICON_BASE_URL}/ic-reading.png`,
    code: 'reading',
    scoring_type: 'auto',
    short_name: '',
    first_question_id: null,
    color: '',
    parent: null,
    practice_count: 0,
    question_count: 0,
    video_link: '',
  },
  {
    id: 11,
    title: 'Fill in the Blanks (Dropdown)',
    description:
      'There are a few words missing in the text below. Please select the correct word from the drop-down box to fill in the gaps.',
    icon: `${ICON_BASE_URL}/rw_fib_production.png`,
    code: 'rw_fib',
    scoring_type: 'auto',
    short_name: 'FIB-RW',
    first_question_id: 13210,
    color: '#5193CD',
    parent: 10,
    practice_count: 0,
    question_count: 387,
    video_link: 'https://youtu.be/5-iIcgayp7s',
  },
  {
    id: 12,
    title: 'MC Multiple Answers (Reading)',
    description:
      'Please read the text and answer the multiple-choice question by selecting the right answer. Keep in mind that there is more than one correct response.',
    icon: `${ICON_BASE_URL}/r_mcq_multiple_production.png`,
    code: 'r_mcq_multiple',
    scoring_type: 'auto',
    short_name: 'MCM-R',
    first_question_id: 34129,
    color: '#3D9DF4',
    parent: 10,
    practice_count: 0,
    question_count: 108,
    video_link: 'https://youtu.be/Y02EdsRXVm0',
  },
  {
    id: 13,
    title: 'Re-order Paragraphs',
    description:
      'The order of the paragraphs below is incorrect. Please drag the paragraphs to rearrange them in the correct sequence.',
    icon: `${ICON_BASE_URL}/r_reorder_paragraphs_production.png`,
    code: 'r_reorder_paragraphs',
    scoring_type: 'auto',
    short_name: 'RO',
    first_question_id: 17776,
    color: '#39B7F2',
    parent: 10,
    practice_count: 0,
    question_count: 200,
    video_link: 'https://youtu.be/IQ9lI92KpkE',
  },
  {
    id: 14,
    title: 'Fill in the Blanks (Drag & Drop)',
    description:
      'There are a few words missing in the text below. Please select the correct word from the dropdown box to fill in the gaps.',
    icon: `${ICON_BASE_URL}/r_fib_production.png`,
    code: 'r_fib',
    scoring_type: 'auto',
    short_name: 'FIB-R',
    first_question_id: 10169,
    color: '#36C8D7',
    parent: 10,
    practice_count: 0,
    question_count: 161,
    video_link: 'https://youtu.be/sntu6-62FFg',
  },
  {
    id: 15,
    title: 'MC Single Answers (Reading)',
    description:
      'Please read the text and answer the multiple-choice question by selecting the right answer. Keep in mind, only one of the responses is correct.',
    icon: `${ICON_BASE_URL}/r_mcq_single_production.png`,
    code: 'r_mcq_single',
    scoring_type: 'auto',
    short_name: 'MCS-R',
    first_question_id: 15368,
    color: '#279F95',
    parent: 10,
    practice_count: 0,
    question_count: 90,
    video_link: 'https://youtu.be/h4WnMBWAFK0',
  },
  {
    id: 16,
    title: 'Listening',
    description: 'Improve Listening',
    icon: `${ICON_BASE_URL}/ic-listening.png`,
    code: 'listening',
    scoring_type: 'auto',
    short_name: '',
    first_question_id: null,
    color: '',
    parent: null,
    practice_count: 0,
    question_count: 0,
    video_link: '',
  },
  {
    id: 17,
    title: 'Summarize Spoken Text',
    description:
      "You're about to hear a brief report. Your task is to write a summary for a fellow student who was absent. Your summary should be between 50-70 words. Remember, you have 10 minutes to accomplish this task. Your response will be graded based on the quality of your writing and how effectively you communicate the key points from the lecture.",
    icon: `${ICON_BASE_URL}/l_summarize_text_production.png`,
    code: 'l_summarize_text',
    scoring_type: 'ai',
    short_name: 'SST',
    first_question_id: 22267,
    color: '#5D7DEE',
    parent: 16,
    practice_count: 0,
    question_count: 152,
    video_link: 'https://youtu.be/vnEc9xF6Fus',
  },
  {
    id: 18,
    title: 'MC Multiple Answers (Listening)',
    description:
      'Please listen to the recording and answer the question by choosing the right answers. Remember, more than one option will be correct for this question.',
    icon: `${ICON_BASE_URL}/l_mcq_multiple_production.png`,
    code: 'l_mcq_multiple',
    scoring_type: 'auto',
    short_name: 'MCM-L',
    first_question_id: 35814,
    color: '#9276DD',
    parent: 16,
    practice_count: 0,
    question_count: 88,
    video_link: 'https://youtu.be/cFbinS4UZnA',
  },
  {
    id: 19,
    title: 'Fill in the Blanks (Listening)',
    description:
      "You're about to hear a recording. Please listen carefully and type the missing words into each blank provided.",
    icon: `${ICON_BASE_URL}/l_fib_production.png`,
    code: 'l_fib',
    scoring_type: 'auto',
    short_name: 'FIB-L',
    first_question_id: 20382,
    color: '#AE78F4',
    parent: 16,
    practice_count: 0,
    question_count: 215,
    video_link: 'https://youtu.be/budK3Q3XpXw',
  },
  {
    id: 20,
    title: 'Highlight Correct Summary',
    description:
      'You will hear a recording. Please click on the paragraph that best corresponds to the content of the recording.',
    icon: `${ICON_BASE_URL}/l_highlight_correct_summary_production.png`,
    code: 'l_highlight_correct_summary',
    scoring_type: 'ai',
    short_name: 'HCS',
    first_question_id: 31541,
    color: '#A866E2',
    parent: 16,
    practice_count: 0,
    question_count: 74,
    video_link: 'https://youtu.be/WmLOiIWh9gQ',
  },
  {
    id: 21,
    title: 'MC Single Answer Listening',
    description:
      'Please listen to the recording and answer the question by selecting the correct answer. Keep in mind, only one of the responses is correct.',
    icon: `${ICON_BASE_URL}/l_mcq_single_production.png`,
    code: 'l_mcq_single',
    scoring_type: 'auto',
    short_name: 'MCS-L',
    first_question_id: 31578,
    color: '#B663BF',
    parent: 16,
    practice_count: 0,
    question_count: 90,
    video_link: 'https://youtu.be/Z1lmnQlSNbU',
  },
  {
    id: 22,
    title: 'Select Missing Word',
    description:
      "You're about to hear a recording about fiction writing. The last word or group of words has been replaced by a beep. Please select the correct option to complete the sentence from the recording.",
    icon: `${ICON_BASE_URL}/l_select_missing_word_production.png`,
    code: 'l_select_missing_word',
    scoring_type: 'auto',
    short_name: 'SMW',
    first_question_id: 28201,
    color: '#BB4D94',
    parent: 16,
    practice_count: 0,
    question_count: 96,
    video_link: 'https://youtu.be/XZ3TFJSZ9JQ',
  },
  {
    id: 23,
    title: 'Highlight Incorrect Words',
    description:
      "You're about to hear a recording. Below it, you'll find a transcription of the recording. Please note, some words in the transcription may differ from what the speaker said. Your task is to identify and click on the words that are different.",
    icon: `${ICON_BASE_URL}/l_highlight_incorrect_words_production.png`,
    code: 'l_highlight_incorrect_words',
    scoring_type: 'auto',
    short_name: 'HIW',
    first_question_id: 18493,
    color: '#B45072',
    parent: 16,
    practice_count: 0,
    question_count: 147,
    video_link: 'https://youtu.be/XDagDHlhUWo',
  },
  {
    id: 24,
    title: 'Write from Dictation',
    description:
      'You will hear a sentence. Listen carefully and write down exactly what you hear. The sentence will be played only once. Accuracy is key in this task. Ensure proper spelling, grammar, and punctuation in your transcription.',
    icon: `${ICON_BASE_URL}/l_write_from_dictation_production.png`,
    code: 'l_write_from_dictation',
    scoring_type: 'auto',
    short_name: 'WFD',
    first_question_id: 24444,
    color: '#CB5C82',
    parent: 16,
    practice_count: 0,
    question_count: 405,
    video_link: 'https://youtu.be/QilK1Afhj_0',
  },
  {
    id: 29,
    title: '[New] Respond to a Situation',
    description:
      'Listen to and read a description of a situation. You will have 10 seconds to think about your answer. Then you will hear a beep. You will have 40 seconds to answer the question. Please answer as completely as you can.',
    icon: `${ICON_BASE_URL}/respond_to_a_situation_academic.png`,
    code: 's_respond_situation_academic',
    scoring_type: 'ai',
    short_name: 'RTS-A',
    first_question_id: 42205,
    color: '#F97962',
    parent: 1,
    practice_count: 0,
    question_count: 48,
    video_link: 'https://youtu.be/BDVmG4HonII',
  },
  {
    id: 30,
    title: '[New] Summarize Group Discussion',
    description:
      'You will hear three people having a discussion. When you hear the beep, summarize the whole discussion. You will have 10 seconds to prepare and 2 minutes to give your response.',
    icon: `${ICON_BASE_URL}/summarize_group_discussion.png`,
    code: 's_summarize_group_discussion',
    scoring_type: 'ai',
    short_name: 'SGD',
    first_question_id: 42221,
    color: '#F97962',
    parent: 1,
    practice_count: 0,
    question_count: 32,
    video_link: 'https://youtu.be/YsjnG_afmyE',
  },
]
