// This file contains a sample dataset for seeding the database.
// It includes one question for each of the 22 question types in PTE Academic.

export const sampleSeedData = {
  speaking: [
    {
      type: 'summarize_group_discussion',
      title: 'Summarize Group Discussion - Sample',
      promptText: 'You will hear a discussion. You have 10 seconds to prepare. Give a summary of the discussion in your own words. You have 2 minutes to give your response.',
      promptMediaUrl: 'https://example.com/audio/sgd-sample.mp3',
      difficulty: 'Medium',
      tags: ['new_question_type', 'academic'],
      isActive: true,
    },
    {
      type: 'respond_to_a_situation',
      title: 'Respond to a Situation - Sample',
      promptText: 'You will hear a description of a situation. You have 10 seconds to think about your answer. Then you will hear a beep. You will have 40 seconds to answer the question.',
      promptMediaUrl: 'https://example.com/audio/rts-sample.mp3',
      difficulty: 'Medium',
      tags: ['new_question_type', 'academic'],
      isActive: true,
    },
    {
      type: 'read_aloud',
      title: 'Read Aloud - Sample',
      promptText: 'Look at the text below. In 40 seconds, you must read this text aloud as naturally and clearly as possible.',
      promptMediaUrl: null,
      difficulty: 'Easy',
      tags: ['pronunciation', 'fluency'],
      isActive: true,
    },
    {
      type: 'repeat_sentence',
      title: 'Repeat Sentence - Sample',
      promptText: 'You will hear a sentence. Please repeat the sentence exactly as you hear it. You will hear the sentence only once.',
      promptMediaUrl: 'https://example.com/audio/rs-sample.mp3',
      difficulty: 'Easy',
      tags: ['listening', 'short-term_memory'],
      isActive: true,
    },
    {
      type: 'describe_image',
      title: 'Describe Image - Sample',
      promptText: 'Look at the image below. In 25 seconds, please speak into the microphone and describe in detail what the image is showing. You will have 40 seconds to give your response.',
      promptMediaUrl: 'https://example.com/images/di-sample.jpg',
      difficulty: 'Medium',
      tags: ['speaking', 'vocabulary'],
      isActive: true,
    },
    {
      type: 'retell_lecture',
      title: 'Retell Lecture - Sample',
      promptText: 'You will hear a lecture. After the lecture, you will have 10 seconds to prepare. Then, in your own words, retell the lecture. You will have 40 seconds to give your response.',
      promptMediaUrl: 'https://example.com/audio/rl-sample.mp3',
      difficulty: 'Hard',
      tags: ['listening', 'speaking', 'summarizing'],
      isActive: true,
    },
    {
      type: 'answer_short_question',
      title: 'Answer Short Question - Sample',
      promptText: 'You will hear a question. Please give a simple and short answer. Often, just one or a few words is enough.',
      promptMediaUrl: 'https://example.com/audio/asq-sample.mp3',
      difficulty: 'Easy',
      tags: ['listening', 'general_knowledge'],
      isActive: true,
    },
  ],
  writing: [
    {
      type: 'summarize_written_text',
      title: 'Summarize Written Text - Sample',
      promptText: 'Read the passage below and summarize it in one sentence. You have 10 minutes to finish this task. Your response will be judged on the quality of your writing and on how well your response presents the key points in the passage.',
      promptMediaUrl: null,
      difficulty: 'Medium',
      tags: ['reading', 'writing', 'summarizing'],
      isActive: true,
    },
    {
      type: 'write_essay',
      title: 'Write Essay - Sample',
      promptText: 'You will have 20 minutes to plan, write and revise an essay about the topic below. Your response will be judged on how well you develop a position, organize your ideas, present supporting details, and control the elements of standard written English. You should write 200-300 words.',
      promptMediaUrl: null,
      difficulty: 'Hard',
      tags: ['writing', 'argumentation', 'structure'],
      isActive: true,
    },
  ],
  reading: [
    {
      type: 'reading_writing_fill_blanks',
      title: 'Reading & Writing: Fill in the blanks - Sample',
      promptText: 'Below is a text with blanks. Click on each blank, a list of choices will appear. Select the appropriate answer for each blank.',
      promptMediaUrl: null,
      difficulty: 'Medium',
      tags: ['reading', 'writing', 'vocabulary'],
      isActive: true,
    },
    {
      type: 'multiple_choice_multiple',
      title: 'Multiple-choice, choose multiple answers - Sample',
      promptText: 'Read the text and answer the question by selecting all the correct responses. More than one response is correct.',
      promptMediaUrl: null,
      difficulty: 'Medium',
      tags: ['reading', 'comprehension'],
      isActive: true,
    },
    {
      type: 'reorder_paragraphs',
      title: 'Re-order paragraphs - Sample',
      promptText: 'The text boxes in the left panel have been placed in a random order. Restore the original order by dragging the text boxes from the left panel to the right panel.',
      promptMediaUrl: null,
      difficulty: 'Hard',
      tags: ['reading', 'structure'],
      isActive: true,
    },
    {
      type: 'reading_fill_blanks',
      title: 'Reading: Fill in the blanks - Sample',
      promptText: 'Below is a text with blanks. Drag words from the box below to the appropriate place in the text. To undo an answer choice, drag the word back to the box below the text.',
      promptMediaUrl: null,
      difficulty: 'Medium',
      tags: ['reading', 'vocabulary'],
      isActive: true,
    },
    {
      type: 'multiple_choice_single',
      title: 'Multiple-choice, choose single answer - Sample',
      promptText: 'Read the text and answer the multiple-choice question by selecting the correct response. Only one response is correct.',
      promptMediaUrl: null,
      difficulty: 'Easy',
      tags: ['reading', 'comprehension'],
      isActive: true,
    },
  ],
  listening: [
    {
      type: 'summarize_spoken_text',
      title: 'Summarize Spoken Text - Sample',
      promptText: 'You will hear a short lecture. Write a summary for a fellow student who was not present at the lecture. You should write 50-70 words. You have 10 minutes to finish this task.',
      promptMediaUrl: 'https://example.com/audio/sst-sample.mp3',
      difficulty: 'Hard',
      tags: ['listening', 'writing', 'summarizing'],
      isActive: true,
    },
    {
      type: 'multiple_choice_multiple',
      title: 'Multiple-choice, choose multiple answers - Sample',
      promptText: 'Listen to the recording and answer the question by selecting all the correct responses. More than one response is correct.',
      promptMediaUrl: 'https://example.com/audio/lmc-multiple-sample.mp3',
      difficulty: 'Medium',
      tags: ['listening', 'comprehension'],
      isActive: true,
    },
    {
      type: 'fill_in_blanks',
      title: 'Fill in the blanks - Sample',
      promptText: 'You will hear a recording. Type the missing words in each blank.',
      promptMediaUrl: 'https://example.com/audio/lfb-sample.mp3',
      difficulty: 'Medium',
      tags: ['listening', 'spelling'],
      isActive: true,
    },
    {
      type: 'highlight_correct_summary',
      title: 'Highlight correct summary - Sample',
      promptText: 'You will hear a recording. Click on the paragraph that best relates to the recording.',
      promptMediaUrl: 'https://example.com/audio/hcs-sample.mp3',
      difficulty: 'Medium',
      tags: ['listening', 'reading', 'comprehension'],
      isActive: true,
    },
    {
      type: 'multiple_choice_single',
      title: 'Multiple-choice, choose single answer - Sample',
      promptText: 'Listen to the recording and answer the multiple-choice question by selecting the correct response. Only one response is correct.',
      promptMediaUrl: 'https://example.com/audio/lmc-single-sample.mp3',
      difficulty: 'Easy',
      tags: ['listening', 'comprehension'],
      isActive: true,
    },
    {
      type: 'select_missing_word',
      title: 'Select missing word - Sample',
      promptText: 'You will hear a recording. At the end of the recording, the last word or group of words has been replaced by a beep. Select the correct option to complete the recording.',
      promptMediaUrl: 'https://example.com/audio/smw-sample.mp3',
      difficulty: 'Easy',
      tags: ['listening', 'comprehension'],
      isActive: true,
    },
    {
      type: 'highlight_incorrect_words',
      title: 'Highlight incorrect words - Sample',
      promptText: 'You will hear a recording. Below is a transcription of the recording. Some words in the transcription differ from what was said. Please click on the words that are different.',
      promptMediaUrl: 'https://example.com/audio/hiw-sample.mp3',
      difficulty: 'Medium',
      tags: ['listening', 'reading', 'attention_to_detail'],
      isActive: true,
    },
    {
      type: 'write_from_dictation',
      title: 'Write from dictation - Sample',
      promptText: 'You will hear a sentence. Type the sentence in the box below exactly as you hear it. Write as much of the sentence as you can. You will hear the sentence only once.',
      promptMediaUrl: 'https://example.com/audio/wfd-sample.mp3',
      difficulty: 'Easy',
      tags: ['listening', 'writing', 'spelling'],
      isActive: true,
    },
  ],
};
